# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_hcd" "firewire_ohci" "usb_storage" "usbhid" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4b076497-f2f8-4e3a-bd27-2874a4a0e361";
    fsType = "ext4";
    options = "noatime,nodiratime,discard";
  };

  fileSystems."/dropbox" = {
    device = "/dev/disk/by-label/vertex";
    fsType = "ext4";
    options = "noatime,nodiratime,discard";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d4e4ae51-9179-439d-925b-8df42dd1bfc5"; } ] ;

  nix.maxJobs = 8;
}
