# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "usb_storage" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.loader.grub.device = "/dev/sdb";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/81ea3402-2a59-4dd5-a86d-5183cd5d6508";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/072733dd-0722-424e-9128-f0ad3d6f2570"; }
    ];

}
